default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  schema_search_path: public

development:
  <<: *default
  database: real_estate_development

test:
  <<: *default
  database: real_estate_test